### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by faijufung** [tomcardoso/sedi-bookmarklet#1]
hi @tomcardoso , thanks so much for putting this together. Huge pain to copy and paste from excel and try to massage.

I was wondering if it's still working for you or if I just can't follow your instructions? I tried firefox + chrome, incognito, JS enabled - but nothing seemed to work?

Thanks in advance for taking a look - working on a side project and was inspecting some trades and found some odd behavior. was hoping to use your tool to look more expansively

**Comment by tomcardoso** [comment]
Hey @faijufung, thanks for the heads up. I suspect that the reason it wasn't working was that you hadn't set a date range for your "insider transaction detail" search – an issue I forgot to document. Instead, I've just [gone in and fixed it](https://github.com/tomcardoso/sedi-bookmarklet/commit/4b6fac2361dc0a9d0b5d28594a6d593a1364e7ce) so that it no longer explicitly expects a date range. Let me know if the bookmarklet works for you now.

**Comment by faijufung** [comment]
thanks @tomcardoso! I tried it again (latest package, incognito), seems to be the same issue. so sorry, I forgot to include the console log last time (see attached). I tried to play around with it to see if I could fix it, but to no avail
![Capture](https://user-images.githubusercontent.com/95063869/144080273-dc721296-6a2c-4581-b8f6-2b9bfc68b3bc.JPG)

**Comment by tomcardoso** [comment]
Ah, I think I see the issue here. You're using the insider transaction detail page without specifying an insider or issuer. The tool wasn't really built to handle that, and it assumes a certain header structure – which the page you requested doesn't hew to.

That said, I don't see why it shouldn't so I've just updated the bookmarklet (https://github.com/tomcardoso/sedi-bookmarklet/commit/9274fe65b82cc37e5e58742414f4ae49d0174569) to account for it. If you already have it in your bookmarks bar it should just work – give it a shot and let me know if you're still running into issues.

**Comment by faijufung** [comment]
@tomcardoso works amazing! thanks so much and thanks for the clarification as well

**Comment by tomcardoso** [comment]
That’s great. Thanks for using the tool!
